#ifndef MAIN_H_
#define MAIN_H_

#define XSHELL_TEST_SHELL_TEST_CTRL_BUS_ADDR_MODE_DATA 0x10
#define XSHELL_TEST_SHELL_TEST_CTRL_BUS_BITS_MODE_DATA 16
#define XSHELL_TEST_SHELL_TEST_CTRL_BUS_ADDR_TEMP_DATA 0x18
#define XSHELL_TEST_SHELL_TEST_CTRL_BUS_BITS_TEMP_DATA 32

#define SHELL_CTRL_BASE XPAR_SHELL_I_M_AXI_CONTROL_BASEADDR
#define SHELL_CTRL_HIGH XPAR_SHELL_I_M_AXI_CONTROL_HIGHADDR

#define SHELL_TEST_MODE_OFFSET XSHELL_TEST_SHELL_TEST_CTRL_BUS_ADDR_MODE_DATA
#define SHELL_TEST_TEMP_OFFSET XSHELL_TEST_SHELL_TEST_CTRL_BUS_ADDR_TEMP_DATA

#include "xil_io.h"

#include "xaxidma.h"
#include "xdebug.h"

#define DMA_DEV_ID		XPAR_AXIDMA_0_DEVICE_ID

#ifdef XPAR_AXI_7SDDR_0_S_AXI_BASEADDR
#define DDR_BASE_ADDR		XPAR_AXI_7SDDR_0_S_AXI_BASEADDR
#elif XPAR_MIG7SERIES_0_BASEADDR
#define DDR_BASE_ADDR	XPAR_MIG7SERIES_0_BASEADDR
#elif XPAR_MIG_0_BASEADDR
#define DDR_BASE_ADDR	XPAR_MIG_0_BASEADDR
#elif XPAR_PSU_DDR_0_S_AXI_BASEADDR
#define DDR_BASE_ADDR	XPAR_PSU_DDR_0_S_AXI_BASEADDR
#endif

#ifndef DDR_BASE_ADDR
#define MEM_BASE_ADDR		XPAR_PS7_DDR_0_S_AXI_BASEADDR
#else
#define MEM_BASE_ADDR		(DDR_BASE_ADDR + 0x1000000)
#endif

#ifdef XPAR_INTC_0_DEVICE_ID
#define RX_INTR_ID		XPAR_INTC_0_AXIDMA_0_S2MM_INTROUT_VEC_ID
#define TX_INTR_ID		XPAR_INTC_0_AXIDMA_0_MM2S_INTROUT_VEC_ID
#else
#define RX_INTR_ID		XPAR_FABRIC_AXIDMA_0_S2MM_INTROUT_VEC_ID
#define TX_INTR_ID		XPAR_FABRIC_AXIDMA_0_MM2S_INTROUT_VEC_ID
#endif

#define BD_ADDR_BASE 0x40000000
#define RX_BD_SPACE_BASE	(BD_ADDR_BASE)
#define RX_BD_SPACE_HIGH	(BD_ADDR_BASE + 0x00000FFF)
#define TX_BD_SPACE_BASE	(BD_ADDR_BASE + 0x00001000)
#define TX_BD_SPACE_HIGH	(BD_ADDR_BASE + 0x00001FFF)
#define TX_BUFFER_BASE		(MEM_BASE_ADDR + 0x00100000)
#define RX_BUFFER_BASE		(MEM_BASE_ADDR + 0x00300000)
#define RX_BUFFER_HIGH		(MEM_BASE_ADDR + 0x004FFFFF)


#define MAX_PKT_LEN		0x100
#define MARK_UNCACHEABLE        0x701

#define TEST_START_VALUE	0xC

extern XAxiDma AxiDma;
extern struct tcp_pcb* pcb;

#endif
